upstream frontend {
  server frontend:80;
}

server {
  listen 80;
  access_log off;
  error_log off;
  return      301 https://avito-plus.ru$request_uri;
}

server {
  listen 443 ssl;
  server_name avito-plus.ru;

  ssl_certificate     /etc/nginx/ssl/avito-plus_ru.full.crt;
  ssl_certificate_key /etc/nginx/ssl/avito-plus_ru.key;

  location / {
    proxy_pass http://frontend;
  }
}

server {
  listen 443 ssl;
  server_name avito-plus.com;

  ssl_certificate     /etc/nginx/ssl/avito-plus_com.full.crt;
  ssl_certificate_key /etc/nginx/ssl/avito-plus_com.key;

  location / {
    proxy_pass http://frontend;
  }
}