upstream validator {
  server validator:3000;
}

upstream stream_mongo_backend {
  server mongo-db:27017;
}

upstream stream_dozzle_backend {
  server mongo-db:6001;
}

server {
  listen 80;
  access_log off;
  error_log off;
  return      301 https://your-domain.example$request_uri;
}

server {
  listen 443 ssl;

  proxy_read_timeout 600s;

  ssl_certificate     /etc/nginx/ssl/your-domain.example.full.crt;
  ssl_certificate_key /etc/nginx/ssl/your-domain.example.key;

  location / {
    proxy_pass http://validator;
  }
}

server {
  listen 27017;
  location / {
    proxy_pass http://mongo-db;
  }
}

server {
  listen 6001;
  location / {
    proxy_pass http://dozzle;
  }
}