// Human-readable descriptions for Avito autoload "section" slugs.
// Mirrors the wording used in the Avito autoload documentation.
export default {
  success_added: 'The ad was added to the site in the latest autoload cycle',
  success_activated: 'The ad was reactivated from previously unpublished or completed listings',
  success_activated_updated: 'The ad was reactivated from previously unpublished or completed listings and edited',
  success_updated: 'The ad was edited',
  success_skipped: 'The ad was left active on the site without changes in this autoload cycle',
  problem_obsolete: 'The ad in the XML uses an obsolete format',
  problem_params_critical: 'Errors related to the description or parameter values occurred while processing the ad. If they are not fixed, the ad will eventually disappear from the site',
  problem_params: 'Errors related to the description or parameter values occurred while processing the ad',
  problem_phone: 'Issues with the phone number in the contact information',
  problem_images: 'Errors occurred while placing the photos',
  problem_vas: 'Errors occurred while activating additional services',
  problem_other: 'An error occurred while processing the ad',
  problem_several: 'Several different errors occurred while processing the ad',
  error_fee: 'The ad was not published because of placement-payment issues',
  error_params: 'Could not be published because of errors related to the description or parameter values',
  error_phone: 'Could not be published because of issues with the phone number in the contact information',
  error_rejected: 'The ad was rejected by moderation for violating the site rules',
  error_blocked: 'The ad was blocked by moderation for violating the site rules',
  error_deleted: 'The ad cannot be processed because an ad with this ID (in the XML file) was previously deleted from the site',
  error_other: 'An error occurred while publishing the ad',
  error_several: 'Several different errors occurred while publishing the ad',
  stopped_end_date_complete: 'Not published or unpublished because the exposure period specified in the XML file has expired',
  stopped_end_date_error: 'Errors occurred while trying to unpublish',
  date_in_future: 'Not published or unpublished because the exposure start date specified in the XML file has not arrived yet',
  publish_later: 'Not added to the site due to the limit on the number of ads published per cycle. To change the autoload mode of your ads, contact Avito support',
  linker: 'Ads similar to ones previously placed via the Avito personal account that require a decision: merge with an existing ad or publish as a new one',
  removed_complete: 'The ad was unpublished (completed) because it was removed from the XML file',
  removed_error: 'Errors while trying to unpublish',
  need_sync: 'The ad is waiting to be synchronized with the site',
  duplicate: 'The ads have identical descriptions',
  without_id: 'The ad has no identifier',
  stopped_by_expiration: 'The placement period has expired', // Not present in swagger
};
